<?php
// includes/insumos_data.php
// Catálogo pequeño de insumos con dosis recomendada por hectárea y precio promedio por unidad (MXN)
// Nota: Ajusta precios/dosis con tu contador; estos son ejemplos para demo.

return [
    [
        'id' => 'urea-46',
        'nombre' => 'Urea 46%',
        'tipo' => 'fertilizante',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 50.0, // kg por ha
        'precio_por_unidad' => 19.0,  // MXN por kg
        'presentacion' => 'Saco 50 kg',
    ],
    [
        'id' => 'dap-18-46-0',
        'nombre' => 'Fosfato Diamónico (DAP 18-46-0)',
        'tipo' => 'fertilizante',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 40.0,
        'precio_por_unidad' => 23.5,
        'presentacion' => 'Saco 50 kg',
    ],
    [
        'id' => 'npk-20-10-10',
        'nombre' => 'Fertilizante NPK 20-10-10',
        'tipo' => 'fertilizante',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 60.0,
        'precio_por_unidad' => 18.2,
        'presentacion' => 'Saco 50 kg',
    ],
    [
        'id' => 'npk-10-10-10',
        'nombre' => 'Fertilizante NPK 10-10-10 (equilibrado)',
        'tipo' => 'fertilizante',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 50.0,
        'precio_por_unidad' => 17.9,
        'presentacion' => 'Saco 50 kg',
    ],
    [
        'id' => 'kcl-60',
        'nombre' => 'Cloruro de Potasio (KCl 60%)',
        'tipo' => 'fertilizante',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 30.0,
        'precio_por_unidad' => 20.5,
        'presentacion' => 'Saco 50 kg',
    ],
    [
        'id' => 'kno3-13-46',
        'nombre' => 'Nitrato de Potasio (13-0-46)',
        'tipo' => 'fertilizante',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 25.0,
        'precio_por_unidad' => 28.0,
        'presentacion' => 'Saco 25 kg',
    ],
    [
        'id' => 'dolomita',
        'nombre' => 'Cal Agrícola (Dolomita)',
        'tipo' => 'enmienda',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 150.0,
        'precio_por_unidad' => 3.8,
        'presentacion' => 'Saco 40 kg',
    ],
    [
        'id' => 'nitrato-calcio',
        'nombre' => 'Nitrato de Calcio (aplicación foliar/suelo)',
        'tipo' => 'fertilizante',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 10.0,
        'precio_por_unidad' => 22.0,
        'presentacion' => 'Saco 25 kg',
    ],
    [
        'id' => 'cloruro-calcio',
        'nombre' => 'Cloruro de Calcio (foliar)',
        'tipo' => 'fertilizante',
        'unidad_dosis' => 'L/ha',
        'dosis_por_hectarea' => 5.0,
        'precio_por_unidad' => 65.0,
        'presentacion' => 'Bidón 20 L',
    ],
    [
        'id' => 'sulfato-magnesio',
        'nombre' => 'Sulfato de Magnesio (Epsomita)',
        'tipo' => 'fertilizante',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 8.0,
        'precio_por_unidad' => 16.0,
        'presentacion' => 'Saco 25 kg',
    ],
    [
        'id' => 'sulfato-zinc',
        'nombre' => 'Sulfato de Zinc (micronutriente)',
        'tipo' => 'micronutriente',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 2.0,
        'precio_por_unidad' => 85.0,
        'presentacion' => 'Saco 25 kg',
    ],
    [
        'id' => 'acido-borico',
        'nombre' => 'Ácido Bórico (Boro, foliar)',
        'tipo' => 'micronutriente',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 1.0,
        'precio_por_unidad' => 140.0,
        'presentacion' => 'Bolsa 5 kg',
    ],
    [
        'id' => 'acidos-humicos',
        'nombre' => 'Ácidos Húmicos y Fúlvicos',
        'tipo' => 'mejorador_suelo',
        'unidad_dosis' => 'L/ha',
        'dosis_por_hectarea' => 10.0,
        'precio_por_unidad' => 75.0,
        'presentacion' => 'Bidón 20 L',
    ],
    [
        'id' => 'glifosato-48',
        'nombre' => 'Herbicida Glifosato 48%',
        'tipo' => 'herbicida',
        'unidad_dosis' => 'L/ha',
        'dosis_por_hectarea' => 3.0, // litros por ha
        'precio_por_unidad' => 120.0, // MXN por litro
        'presentacion' => 'Bidón 20 L',
    ],
    [
        'id' => '24d-amine',
        'nombre' => 'Herbicida 2,4-D Amine',
        'tipo' => 'herbicida',
        'unidad_dosis' => 'L/ha',
        'dosis_por_hectarea' => 2.0,
        'precio_por_unidad' => 95.0,
        'presentacion' => 'Bidón 20 L',
    ],
    [
        'id' => 'imidacloprid-350',
        'nombre' => 'Insecticida Imidacloprid 350 g/L',
        'tipo' => 'insecticida',
        'unidad_dosis' => 'L/ha',
        'dosis_por_hectarea' => 0.4,
        'precio_por_unidad' => 480.0,
        'presentacion' => 'Botella 1 L',
    ],
    [
        'id' => 'mancozeb-80',
        'nombre' => 'Fungicida Mancozeb 80%',
        'tipo' => 'fungicida',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 2.0,
        'precio_por_unidad' => 110.0,
        'presentacion' => 'Saco 25 kg',
    ],
    [
        'id' => 'cobre-oxicloruro',
        'nombre' => 'Fungicida Oxicloruro de Cobre 85%',
        'tipo' => 'fungicida',
        'unidad_dosis' => 'kg/ha',
        'dosis_por_hectarea' => 3.0,
        'precio_por_unidad' => 98.0,
        'presentacion' => 'Saco 25 kg',
    ],
];
